# Generated by Django 3.1.5 on 2021-01-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekonstruksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
