# Generated by Django 3.1.5 on 2021-01-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekonstruksi', '0004_remove_post_texture_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
