# Generated by Django 3.1.5 on 2021-02-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekonstruksi', '0006_auto_20210204_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
